var Exemplos = '';
var OlaMundo = 'escreva("Olá, mundo!");';
var Classe = "classe Animal {\n  correr() {\n      escreva(\"Correndo Loucamente\");\n  }\n}\nclasse Cachorro herda Animal {\n  latir() {\n      escreva(\"Au Au Au Au\");\n  }\n}\nvar nomeDoCachorro = Cachorro();\nnomeDoCachorro.correr();\nnomeDoCachorro.latir();";
var MergeSort = "var vetor1 = [8, 2, 9, 5];\nvar a=0;\nvar aux=0;\nvar i=0;\nescreva (\"Vetor: Posi\u00E7\u00E3o[0]:\"+texto(vetor1[0]));\nescreva (\"Vetor: Posi\u00E7\u00E3o[1]:\"+texto(vetor1[1]));\nescreva (\"Vetor: Posi\u00E7\u00E3o[2]:\"+texto(vetor1[2]));\nescreva (\"Vetor: Posi\u00E7\u00E3o[3]:\"+texto(vetor1[3]));\npara (i=0; i<3; i=i+1){\n  se (vetor1[i]>vetor1[i+1]){\n    \n    escreva (\"Vetor \"+texto(i));\n    aux = vetor1[i];\n    vetor1[i] = vetor1[i+1];\n    vetor1[i+1] = aux;\n    escreva(vetor1[i]);\n    escreva(vetor1[i+1]);\n  }\n}\nvar vetor2 = [vetor1[0], vetor1[1]];\nvar vetor3 = [vetor1[2], vetor1[3]];\nvar vetor4 = [];\npara (a=0; a<4; a=a+1){\n  escreva (\"vetor1(\"+texto(a)+\")\");\n  escreva (vetor1[a]);\n}\npara (a=0; a<2; a=a+1){\n  escreva (\"vetor2(\"+texto(a)+\")\");\n  escreva (vetor2[a]);\n}\npara (a=0; a<2; a=a+1){\n  escreva (\"vetor3(\"+texto(a)+\")\");\n  escreva (vetor3[a]);\n}\nse (vetor2[0]<vetor3[0] e vetor2[1]<vetor3[1]){\n  vetor4[0]=vetor2[0];\n  se (vetor3[0]<vetor2[1]){\n  vetor4[1]=vetor3[0];\n  vetor4[2]=vetor2[1];\n  vetor4[3]=vetor3[1];\n  }senao{\n  vetor4[1]=vetor2[1];\n  vetor4[2]=vetor3[0];\n  vetor4[3]=vetor3[1];\n  }\n}\n    \npara (a=0; a<4; a=a+1){\n  escreva (\"vetor4(\"+texto(vetor4[a])+\")\");\n}";
var Bhaskara = "funcao bhaskara(a,b,c){\n  //A vari\u00E1vel \"d\" vai simbolizar o Delta.\n  //\"a\", \"b\", e \"c\" ir\u00E3o representar os coeficientes da equa\u00E7\u00E3o.\n  var d = b**2;\n        var f = 4*a*c; \n  d = d-f;\n  escreva(\"O valor de Delta \u00E9: \" + texto(d));\n  d = d**0.5;\n  \n  //Encontrando os valores de X1 e X2.\n  var x1 = -b+d;\n  x1 = x1/2*a;\n  escreva(\"O valor de X1 \u00E9: \"+ texto(x1));\n  var x2 = -b-d;\n  x2 = x2/2*a;\n  escreva(\"O valor de X2 \u00E9: \"+ texto(x2));\n  //Resultado das substitui\u00E7\u00F5es de X por X1 e X2 na equa\u00E7\u00E3o.\n  var r1 = x1**2;\n  r1 = a*r1;\n  r1 = b*x1 + r1;\n  r1 = r1 + c;\n  escreva(\"Substituindo X1 na equa\u00E7\u00E3o obt\u00E9m-se:\"+ texto(r1));\n  var r2 = x2**2;\n  r2 = a*r2;\n  r2 = b*x2 + r2;\n  r2 = r2 + c;\n  escreva(\"Substituindo X2 na equa\u00E7\u00E3o obt\u00E9m-se:\"+ texto(r2));\n}\n\n//Insira o valor do coeficiente A:\n var a = 1;\n\n//Insira o valor do coeficiente B:\n var b = -1;\n\n//Insira o valor do coeficiente B:\n var c = -30;\n\nbhaskara(a,b,c);";
var Fibonacci = "// Recurs\u00E3o para o c\u00E1lculo da sequ\u00EAncia de fibonacci\n\nfuncao fibonacci(n){\n  se(n==0){\n    retorna(0);\n }senao{\n    se(n==1){\n      retorna(1);\n   }senao{\n    var n1 = n-1;\n    var n2 = n-2;\n    var f1 = fibonacci(n1);\n    var f2 = fibonacci(n2);\n    retorna(f1 + f2);}\n  }\n}\n\nvar a = fibonacci(0);\nescreva(a);\na = fibonacci(1);\nescreva(a);\na = fibonacci(2);\nescreva(a);\na = fibonacci(3);\nescreva(a);\na = fibonacci(4);\nescreva(a);\na = fibonacci(5);\nescreva(a);";
var Perceptron = "var pesoInicial1 = 0.3;\nvar pesoInicial2 = 0.4;\n\nvar entrada1 = 1;\nvar entrada2 = 1;\n\nvar erro = 1;\n\nvar resultadoEsperado;\n\nenquanto(erro!=0){\n  se(entrada1 == 1){\n    se(entrada2 == 1){\n      resultadoEsperado = 1;\n    }\n  } senao {\n    resultadoEsperado = 0;\n  }\n  \n  var somatoria = pesoInicial1 * entrada1;\n  somatoria = pesoInicial2 * entrada2 + somatoria;\n  \n  var resultado;\n  \n  se(somatoria < 1){\n    resultado = 0;\n  } senao{\n    se(somatoria>=1){\n      resultado = 1;\n    }\n  }\n  \n  escreva(\"resultado: \" + texto(resultado));\n  \n  erro = resultadoEsperado - resultado;\n\n  escreva(\"p1: \" + texto(pesoInicial1));\n  escreva(\"p2: \" + texto(pesoInicial2));\n\n  pesoInicial1 = 0.1 * entrada1 * erro + pesoInicial1;\n  pesoInicial2 = 0.1 * entrada2 * erro + pesoInicial2;\n\n  escreva(\"erro: \" + texto(erro));\n}";
var FilaEstatica = "funcao enfileirar (valorEntrada) {\n  se (indexFinal == maximoDeElementos){\n    escreva(\"Fila Cheia\");\n  } senao {\n    filaEstatica[indexFinal] = valorEntrada;\n    escreva(\"Valor inserido com sucesso: \" + texto(filaEstatica[indexFinal]));\n    retorna indexFinal = indexFinal + 1;\n  }\n}\n\nfuncao desenfileirar(){\n  se (indexInicial == indexFinal){\n    escreva(\"Fila Vazia\") ;\n  } senao {\n    para (i = 0; i <= indexFinal; i=i+1){\n      \n      se(i+1 == indexFinal){\n        indexFinal = indexFinal - 1;\n        escreva(\"Valor retirado com sucesso.\");\n        \n      } senao {\n        filaEstatica[i] = filaEstatica[i+1];\n      }\n    }    \n  }\n}\n\nfuncao mostrar_fila () {\n  se(indexInicial == indexFinal){\n    escreva(\"Fila Vazia\");\n  } senao {  \n    para (var i = 0; i < indexFinal; i = i + 1){\n      escreva(\"index \"+texto(i)); \n      escreva(texto(filaEstatica[i]));\n    }\n  }\n}\n\nvar maximoDeElementos = 4;\nvar indexInicial = 0;\nvar indexFinal = 0;\n\n//Variavel de controle em itera\u00E7\u00F5es\nvar i = 0;\n\n\nvar filaEstatica = [];\n\n\n//Demonstra\u00E7\u00E3o de uso das fun\u00E7\u00F5es:\nmostrar_fila();\n\nvar valorEntrada = 2;\nenfileirar(valorEntrada);\n\nvar valorEntrada = 8;\nenfileirar(valorEntrada);\n\nvar valorEntrada = 23;\nenfileirar(valorEntrada);\n\nvar valorEntrada = 7;\nenfileirar(valorEntrada);\n\nmostrar_fila();\n\ndesenfileirar();\n\nmostrar_fila();\n\nvar valorEntrada = 24;\nenfileirar(valorEntrada);\n\nmostrar_fila();";
var demos = {
    Exemplos: Exemplos,
    OlaMundo: OlaMundo,
    Classe: Classe,
    MergeSort: MergeSort,
    Bhaskara: Bhaskara,
    Fibonacci: Fibonacci,
    Perceptron: Perceptron,
    FilaEstatica: FilaEstatica
};
//# sourceMappingURL=exemplos.js.map